// Copyright (c) 2024 AlakhService. All rights reserved.
// Bootstrap initialisation — called from [main] after the Flutter binding
// is ready and the error zone is established.

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'app.dart';
import 'main.dart';

/// Performs all async initialisation work before running the Flutter app.
///
/// Order of operations:
/// 1. Initialise dependency injection container.
/// 2. Initialise Firebase (core, crashlytics, analytics, messaging).
/// 3. Set up push-notification channels and request permissions.
/// 4. Configure Hive / local storage.
/// 5. Set up network-connectivity listener.
/// 6. Register deep-link handlers.
/// 7. Initialise feature-flags client.
/// 8. Set system UI overlay style.
/// 9. Hand off to [runApp].
Future<void> bootstrap({required Env env}) async {
  // ------------------------------------------------------------------
  // 1. Dependency injection
  // ------------------------------------------------------------------
  await _initDependencies(env);

  // ------------------------------------------------------------------
  // 2. Firebase
  // ------------------------------------------------------------------
  await _initFirebase();

  // ------------------------------------------------------------------
  // 3. Local storage (Hive)
  // ------------------------------------------------------------------
  await _initLocalStorage();

  // ------------------------------------------------------------------
  // 4. System UI
  // ------------------------------------------------------------------
  _configureSystemUI();

  // ------------------------------------------------------------------
  // 5. Run the app
  // ------------------------------------------------------------------
  runApp(App(env: env));
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// Registers all service-locator bindings.
Future<void> _initDependencies(Env env) async {
  // TODO(di): Call `configureDependencies(env)` once the generated
  // injectable module is wired up.
  // await configureDependencies(
  //   environment: env.flavor,
  //   environmentConfig: EnvironmentConfig(
  //     apiBaseUrl: env.apiBaseUrl,
  //     useMockServices: env.useMockServices,
  //   ),
  // );
  debugPrint('[Bootstrap] Dependency injection initialised (${env.flavor})');
}

/// Initialises Firebase services.
Future<void> _initFirebase() async {
  // TODO(firebase): Uncomment when firebase_options.dart is generated via
  // `flutterfire configure`.
  //
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );
  //
  // // Crashlytics
  // await FirebaseCrashlytics.instance
  //     .setCrashlyticsCollectionEnabled(!kDebugMode);
  // FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
  //
  // // Analytics
  // await FirebaseAnalytics.instance.setAnalyticsCollectionEnabled(!kDebugMode);
  //
  // // Messaging — request permission and get FCM token
  // final messaging = FirebaseMessaging.instance;
  // await messaging.requestPermission(
  //   alert: true,
  //   badge: true,
  //   sound: true,
  // );
  // final token = await messaging.getToken();
  // debugPrint('[Bootstrap] FCM token: $token');
  debugPrint('[Bootstrap] Firebase initialisation skipped (stub)');
}

/// Initialises Hive and registers all adapters.
Future<void> _initLocalStorage() async {
  // TODO(hive): Uncomment once Hive adapters are generated.
  //
  // final appDir = await getApplicationDocumentsDirectory();
  // Hive.init(appDir.path);
  //
  // // Register type adapters generated by hive_generator
  // if (!Hive.isAdapterRegistered(UserAdapter().typeId)) {
  //   Hive.registerAdapter(UserAdapter());
  // }
  //
  // await Hive.openBox<dynamic>(kSettingsBox);
  // await Hive.openBox<dynamic>(kCacheBox);
  debugPrint('[Bootstrap] Local storage initialised (stub)');
}

/// Applies the preferred system UI overlay style for the entire app.
void _configureSystemUI() {
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      statusBarBrightness: Brightness.light,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );
}
